/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "axtczypotrjjzvgqdqlw"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_PUBLIC_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dGN6eXBvdHJqanp2Z3FkcWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTI4ODksImV4cCI6MjA4Njg4ODg4OX0.vVRXESr_s4i5TMYGlMa3AEx5Xcf3gkRrcwqW0zj3l8E"